server:
  servlet:
    context-path: /megacampaign

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  
  datasource:
    url: jdbc:postgresql://localhost:5432/megacampaign
    username: megacampaign
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

discord:
  notification:
    enabled: true
  api:
    endpoint: ${DISCORD_API_ENDPOINT:}